### ISSUE TITLE
Questions regarding UNETR in Table 1

### ISSUE THREAD

**Issue by qinliuliuqin** [csyfjiang/U-MLLA#3]
@csyfjiang Thanks for your great work! 

In Table 1, UNETR is a 3D segmentation method, whereas your method is 2D, right? Did you retrain all the baseline methods on each dataset? I appreciate more details on this table. Thank you in advance.

**Comment by csyfjiang** [comment]
@qinliuliuqin 
Yes, I used MONAI or the offical implementation of these baseline for retraining on the same datasets.

Some of missing results caused by the training processing cannot converge or the code is not complete.

Hope it helps!

**Comment by qinliuliuqin** [comment]
@csyfjiang  
Thank you for your prompt response. It may be beneficial to clearly distinguish between 2D and 3D methods in the paper, as they involve different training and evaluation protocols. For instance, 2D methods are typically trained and evaluated on 2D slices, whereas 3D methods are trained and evaluated on volumes.

Additionally, the paper does not specify the training details for each baseline, such as input/cropped size and the number of training epochs or iterations, which could enhance clarity and reproducibility.

**Comment by csyfjiang** [comment]
@qinliuliuqin 
Thanks for your suggestions

I will update our manuscript if it would be accpeted.
